name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo 안녕하세요??
    - name: Run a multi-line script
      run: |
        echo 만나서 반가워요!
        echo 오늘은 날씨가 좋네욬ㅋㅋ
